# Generated by Django 3.2.5 on 2021-07-16 13:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cafe5', '0003_auto_20210715_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='menuitems',
            name='estimated_cooking_time',
        ),
        migrations.RemoveField(
            model_name='menuitems',
            name='serving_time_period',
        ),
        migrations.AddField(
            model_name='menuitems',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='date of creation of item', verbose_name='date of adding item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitems',
            name='image',
            field=models.FileField(help_text='upload image of item', null=True, upload_to='cafe5/menu_items/images/', verbose_name='item image'),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='modify_timestamp',
            field=models.DateTimeField(auto_now=True, help_text='date of modify of item', verbose_name='date of update item'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='discount',
            field=models.IntegerField(blank=True, default=0, help_text='enter item discount', null=True, verbose_name='item discount'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='name',
            field=models.CharField(help_text='enter menu item name', max_length=30, verbose_name='menu item name'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='price',
            field=models.FloatField(help_text='enter item price', verbose_name='item price'),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='time_stamp',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 7, 16, 13, 18, 29, 264027)),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='category',
            field=models.ForeignKey(help_text='define category', on_delete=django.db.models.deletion.CASCADE, to='cafe5.category', verbose_name='menu item category'),
        ),
    ]
