# Generated by Django 3.2.5 on 2021-07-15 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe5', '0002_auto_20210708_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='time_stamp',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 7, 15, 11, 44, 25, 735212)),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.CharField(max_length=3),
        ),
    ]
