# Generated by Django 3.2.5 on 2021-07-19 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe5', '0006_alter_receipts_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='image',
            field=models.FileField(blank=True, help_text='upload image of item', null=True, upload_to='cafe5/menu_items/images/', verbose_name='item image'),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='time_stamp',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 7, 19, 15, 34, 32, 570459)),
        ),
    ]
