# Generated by Django 3.2.5 on 2021-07-19 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe5', '0008_alter_receipts_time_stamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='table_id',
        ),
        migrations.AddField(
            model_name='orders',
            name='table_id',
            field=models.ManyToManyField(to='cafe5.Table'),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='time_stamp',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 7, 19, 19, 35, 56, 373313)),
        ),
    ]
