# Generated by Django 3.2.5 on 2021-07-19 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe5', '0009_auto_20210719_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='menu_item_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orders',
            name='table_id',
            field=models.ManyToManyField(related_name='orders', to='cafe5.Table'),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='time_stamp',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 7, 19, 19, 56, 24, 721817)),
        ),
    ]
