# Generated by Django 3.2.5 on 2021-07-22 08:07

import datetime
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cafe5', '0011_auto_20210719_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('modify_timestamp', models.DateTimeField(auto_now=True)),
                ('delete_timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('phone_number', models.CharField(help_text='enter your phone', max_length=11, verbose_name='phone number')),
                ('national_code', models.CharField(help_text='enter your national code', max_length=10, verbose_name='national code')),
                ('address', models.TextField(max_length=50)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_number',
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='time_stamp',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 7, 22, 8, 7, 51, 900285)),
        ),
    ]
