# Generated by Django 3.2.5 on 2021-07-19 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe5', '0007_auto_20210719_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='time_stamp',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 7, 19, 19, 15, 12, 681991)),
        ),
    ]
