# Generated by Django 3.2.5 on 2021-07-29 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyBaseModel',
        ),
    ]
