# Generated by Django 3.2.5 on 2021-07-19 19:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe5', '0010_auto_20210719_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='menu_item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cafe5.menuitems'),
        ),
        migrations.RemoveField(
            model_name='orders',
            name='table_id',
        ),
        migrations.AddField(
            model_name='orders',
            name='table_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='cafe5.table'),
        ),
        migrations.RemoveField(
            model_name='receipts',
            name='orders_id',
        ),
        migrations.AddField(
            model_name='receipts',
            name='orders_id',
            field=models.ManyToManyField(to='cafe5.Orders'),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='time_stamp',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 7, 19, 19, 59, 46, 708837)),
        ),
    ]
