# Generated by Django 3.2.5 on 2021-07-08 13:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('discount', models.IntegerField()),
                ('price', models.FloatField()),
                ('serving_time_period', models.IntegerField()),
                ('estimated_cooking_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('time_stamp', models.DateTimeField(verbose_name=datetime.datetime(2021, 7, 8, 13, 0, 6, 765630))),
                ('menu_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe5.menuitems')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
                ('cafe_space_position', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField()),
                ('final_price', models.FloatField()),
                ('time_stamp', models.DateTimeField(verbose_name=datetime.datetime(2021, 7, 8, 13, 0, 6, 766103))),
                ('orders_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe5.orders')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='table_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe5.table'),
        ),
    ]
